### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.
spring:
  profiles:
    active:
      mysql
  cloud:
    config:
      uri: http://localhost:9000
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-host1:8761/eureka/,http://eureka-host2:8762/eureka/

spring.jmx:
  enabled: false
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/rsmortgage;MODE=MySQL

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 9002
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: udemy-rsmortgage-customer-service
  version: 1.0
  description: RSMortgage Customer REST MicroService
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}